#!/usr/bin/env bash
set -euo pipefail

sudo echo 'Thanks'

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT
pushd $TMP

# ====================
# Set up directories
# ====================
mkdir -p ~/re/dev
mkdir ~/re/src
mkdir ~/tmp

# ====================
# Install necessities
# ====================
export DEBIAN_FRONTEND=noninteractive
sudo apt update
# My tools
sudo apt install -qy neovim fish fzf exa flameshot pyenv ncdu bfs python3-venv sqlite3 nodejs npm jq
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Pentesting tools (and upgrade existing)
sudo apt install -qy gobuster dirsearch rlwrap shellter kerberoast seclists nishang ncat radare2 gdb rustscan guake searchsploit wpscan nikto

# ====================
# Adjust timezone
# ====================
echo "TZ='America/Los_Angeles'; export TZ" >> ~/.profile

# ====================
# Set up fish
# ====================
chsh -s /usr/bin/fish kali
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fish -c 'omf update'

# ====================
# Set up syncthing
# ====================
syncthing_latest=$(curl https://syncthing.net/downloads/ | grep -Po 'https://github.com/.*linux-amd64.*tar.gz')
curl -o syncthing.tar.gz $syncthing_latest
tar xf syncthing.tar.gz
pushd syncthing-*
sudo install -D syncthing /usr/local/bin/syncthing
sudo install -Dm644 etc/linux-systemd/user/syncthing.service /etc/systemd/user/syncthing.service
systemctl --user enable --now syncthing
spd-say 'Set up Syncthing'
open 'http://localhost:8384'
popd

# ====================
# Set up flameshot
# ====================
xfconf-query -c xfce4-keyboard-shortcuts -n -t 'string' -p '/commands/custom/<Shift><Super>s' -s 'flameshot gui'

# ====================
# Set up metasploit
# ====================
sudo systemctl enable --now postgresql
sudo msfdb init

# ====================
# Set up git
# ====================
git config --global user.name 'Zhenkai Weng'
git config --global user.email 'theoaktree1040@gmail.com'
spd-say 'Enter SSH passphrase'
ssh-keygen -t ed25519 -a 100 -f ~/.ssh/id_ed25519

# ====================
# Set up obsidian
# ====================
obsidian_latest=$(curl https://obsidian.md/ | tee | grep -Po 'https://.*AppImage' -m 1)
curl -o obsidian $obsidian_latest
sudo install obsidian /usr/local/bin/obsidian

# ====================
# Set up guake
# ====================
# TODO: guake: add keyboard shortcut Ctrl-G
# TODO: guake: autostart
# TODO: guake: set colorscheme to nord

# ====================
# Set up neovim
# ====================
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
sudo install nvim.appimage /usr/local/bin/nvim
packer_url='https://github.com/wbthomason/packer.nvim'
packer_dst='~/.local/share/nvim/site/pack/packer/start/packer.nvim'
git clone --depth 1 $packer_url $packer_dst
nvim -c 'PackerSync' -es
nvim -c 'COQdeps' -es
nvim -c 'PackerSnapshot initial' -es

# ====================
# Set up gdb / pwndbg
# ====================
$pwndbg=$user/re/src/pwndbg
git clone https://github.com/pwndbg/pwndbg $pwndbg
pushd $pwndbg
./setup.sh
echo 'set disassembly-flavor intel' >> ~/.gdbinit
popd

